
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag token-bouncer:$(date +%s)
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Archive Docker image
        uses: actions/upload-artifact@v2
        with:
          name: token-bouncer
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-${{ github.run_id }}
          release_name: Release ${{ github.run_number }}-${{ github.run_id }}
          body: |
            Release of version main.

            ## Docker Image
            ```
            docker pull token-bouncer:$(date +%s)
            ```
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .
          asset_name: token-bouncer:$(date +%s) # Update the asset name as per your Docker image tag
          asset_content_type: application/octet-stream
